### ISSUE TITLE
InaccessibleObjectException crash with ConfigAnytime

### ISSUE THREAD

**Issue by kingof99kings** [TwilightFlower/lwjgl3ify#1]
upon relaunching minecraft with lwjgl3ify und ConfigAnytime, which is required for Universal Tweaks, it crashes.

[latest.log](https://github.com/user-attachments/files/15831279/latest.log)

**Comment by kappa-maintainer** [comment]
You will need extra --add-opens jvm flag to open java.base module
Btw [Cleanroom](https://github.com/CleanroomMC/Cleanroom) exists if you want a more mature solution

**Comment by kingof99kings** [comment]
thank you very much

**Comment by TwilightFlower** [comment]
@kappa-maintainer, please refrain from advertising on this issue tracker.

**Comment by kappa-maintainer** [comment]
Alright, just want to make sure you know
We can still improve each project on the patching topic though
